apiVersion: v1
kind: Service
metadata:
  name: dockerassignment-service
spec:
  selector:
    app: dockerassignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 
